(SuicidePrediction) jaineel@JP-LAPTOP:/mnt/c/Users/JP/Documents/Mental-Geek_Leap/Suicide-Prediction$ python3 app.py
2021-08-20 22:29:18.312523: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2021-08-20 22:29:18.314490: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
 * Serving Flask app 'app' (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: on
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
 * Restarting with stat
2021-08-20 22:29:29.026071: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2021-08-20 22:29:29.026377: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
 * Debugger is active!
 * Debugger PIN: 138-128-177
127.0.0.1 - - [20/Aug/2021 22:29:50] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [20/Aug/2021 22:29:54] "GET /static/css/index.css HTTP/1.1" 304 -
127.0.0.1 - - [20/Aug/2021 22:29:55] "GET /static/css/bg.jpg HTTP/1.1" 304 -
127.0.0.1 - - [20/Aug/2021 22:30:06] "GET /input HTTP/1.1" 200 -
127.0.0.1 - - [20/Aug/2021 22:30:06] "GET /static/css/upload.css HTTP/1.1" 304 -
127.0.0.1 - - [20/Aug/2021 22:30:07] "GET /static/css/background.jpg HTTP/1.1" 304 -
127.0.0.1 - - [20/Aug/2021 22:30:07] "GET /mental%20health.jpg HTTP/1.1" 404 -
127.0.0.1 - - [20/Aug/2021 22:30:14] "POST /upload HTTP/1.1" 302 -
Data is loaded
Data Loaded and Checked
Data Cleaned
Data Encoded


Correlation Matrix:

                   family_size  annual_income  eating_habits  ...   anxiety  happy_currently  suicidal_thoughts
family_size           1.000000      -0.042214       0.066318  ...  0.162366        -0.050309           0.080420
annual_income        -0.042214       1.000000      -0.089304  ... -0.133055         0.042194          -0.144129
eating_habits         0.066318      -0.089304       1.000000  ...  0.061451        -0.109776           0.083808
addiction_friend      0.023710       0.119274      -0.063661  ...  0.100138        -0.034929          -0.091548
addiction             0.032259       0.055304       0.068245  ...  0.097530        -0.078782          -0.032259
medical_history       0.175749      -0.264076       0.106260  ...  0.412722        -0.190702           0.266967
depressed             0.053648      -0.144553      -0.033087  ...  0.285102        -0.498167           0.297989
anxiety               0.162366      -0.133055       0.061451  ...  1.000000        -0.245867           0.377108
happy_currently      -0.050309       0.042194      -0.109776  ... -0.245867         1.000000          -0.408260
suicidal_thoughts     0.080420      -0.144129       0.083808  ...  0.377108        -0.408260           1.000000

[10 rows x 10 columns]


/mnt/c/Users/JP/Documents/Mental-Geek_Leap/Suicide-Prediction/src/CorrelationMatrix.py:12: UserWarning: Starting a Matplotlib GUI outside of the main thread will likely fail.
  f, ax = plt.subplots(figsize=(9, 9))
/mnt/c/Users/JP/Documents/Mental-Geek_Leap/Suicide-Prediction/src/FeatureImportance.py:23: UserWarning: Starting a Matplotlib GUI outside of the main thread will likely fail.
  plt.figure(figsize=(12,8))

Tuning the Logistic Regression Model with GridSearchCV

/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/linear_model/_sag.py:328: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn("The max_iter was reached which means "
/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/linear_model/_sag.py:328: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn("The max_iter was reached which means "
/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/linear_model/_sag.py:328: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn("The max_iter was reached which means "
/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/linear_model/_sag.py:328: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn("The max_iter was reached which means "
/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/linear_model/_sag.py:328: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn("The max_iter was reached which means "
/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/linear_model/_sag.py:328: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn("The max_iter was reached which means "
/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/linear_model/_sag.py:328: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn("The max_iter was reached which means "
/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/linear_model/_sag.py:328: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn("The max_iter was reached which means "
/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/linear_model/_sag.py:328: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn("The max_iter was reached which means "
/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/linear_model/_sag.py:328: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn("The max_iter was reached which means "
/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/linear_model/_sag.py:328: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn("The max_iter was reached which means "
/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/linear_model/_sag.py:328: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn("The max_iter was reached which means "
/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/linear_model/_sag.py:328: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn("The max_iter was reached which means "
/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/linear_model/_sag.py:328: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn("The max_iter was reached which means "
/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/linear_model/_sag.py:328: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn("The max_iter was reached which means "
/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/linear_model/_sag.py:328: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn("The max_iter was reached which means "
/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/linear_model/_sag.py:328: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn("The max_iter was reached which means "
/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/linear_model/_sag.py:328: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn("The max_iter was reached which means "
/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/linear_model/_sag.py:328: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn("The max_iter was reached which means "
/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/linear_model/_sag.py:328: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn("The max_iter was reached which means "
/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/linear_model/_sag.py:328: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn("The max_iter was reached which means "
/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/linear_model/_sag.py:328: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn("The max_iter was reached which means "
/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/linear_model/_sag.py:328: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn("The max_iter was reached which means "
/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/linear_model/_sag.py:328: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn("The max_iter was reached which means "
/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/linear_model/_sag.py:328: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn("The max_iter was reached which means "
/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/linear_model/_sag.py:328: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn("The max_iter was reached which means "
/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/linear_model/_sag.py:328: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn("The max_iter was reached which means "
/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/linear_model/_sag.py:328: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn("The max_iter was reached which means "
/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/linear_model/_sag.py:328: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn("The max_iter was reached which means "
/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/linear_model/_sag.py:328: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn("The max_iter was reached which means "
/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/linear_model/_sag.py:328: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn("The max_iter was reached which means "
/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/linear_model/_sag.py:328: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn("The max_iter was reached which means "
/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/linear_model/_sag.py:328: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn("The max_iter was reached which means "
/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/linear_model/_sag.py:328: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn("The max_iter was reached which means "
/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/linear_model/_sag.py:328: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn("The max_iter was reached which means "
/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/linear_model/_sag.py:328: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn("The max_iter was reached which means "
/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/linear_model/_sag.py:328: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn("The max_iter was reached which means "
/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/linear_model/_sag.py:328: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn("The max_iter was reached which means "
/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/linear_model/_sag.py:328: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn("The max_iter was reached which means "
/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/linear_model/_sag.py:328: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn("The max_iter was reached which means "
/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/linear_model/_sag.py:328: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn("The max_iter was reached which means "
/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/linear_model/_sag.py:328: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn("The max_iter was reached which means "
/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/linear_model/_sag.py:328: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn("The max_iter was reached which means "
/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/linear_model/_sag.py:328: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn("The max_iter was reached which means "
/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/linear_model/_sag.py:328: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn("The max_iter was reached which means "
/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/linear_model/_sag.py:328: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn("The max_iter was reached which means "
/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/linear_model/_sag.py:328: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn("The max_iter was reached which means "
/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/linear_model/_sag.py:328: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn("The max_iter was reached which means "
/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/linear_model/_sag.py:328: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn("The max_iter was reached which means "
/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/linear_model/_sag.py:328: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn("The max_iter was reached which means "
/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/linear_model/_sag.py:328: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn("The max_iter was reached which means "
/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/linear_model/_sag.py:328: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn("The max_iter was reached which means "
/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/linear_model/_sag.py:328: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn("The max_iter was reached which means "

Tuning KNN model with GridSearchCV


Tuning Decision Tree model with GridSearchCV


Tuning Random Forest model with GridSearchCV


Tuning Boosting model with GridSearchCV


Tuning Bagging model with GridSearchCV


Tuning Stacking model with GridSearchCV

/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/model_selection/_validation.py", line 598, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/ensemble/_stacking.py", line 441, in fit
    return super().fit(X, self._le.transform(y), sample_weight)
  File "/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/ensemble/_stacking.py", line 172, in fit
    self.stack_method_ = [
  File "/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/ensemble/_stacking.py", line 173, in <listcomp>
    self._method_name(name, est, meth)
  File "/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/ensemble/_stacking.py", line 108, in _method_name
    raise ValueError('Underlying estimator {} does not implement '
ValueError: Underlying estimator rf does not implement the method decision_function.

  warnings.warn("Estimator fit failed. The score on this train-test"
/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/model_selection/_validation.py", line 598, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/ensemble/_stacking.py", line 441, in fit
    return super().fit(X, self._le.transform(y), sample_weight)
  File "/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/ensemble/_stacking.py", line 172, in fit
    self.stack_method_ = [
  File "/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/ensemble/_stacking.py", line 173, in <listcomp>
    self._method_name(name, est, meth)
  File "/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/ensemble/_stacking.py", line 108, in _method_name
    raise ValueError('Underlying estimator {} does not implement '
ValueError: Underlying estimator rf does not implement the method decision_function.

  warnings.warn("Estimator fit failed. The score on this train-test"
/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/model_selection/_validation.py", line 598, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/ensemble/_stacking.py", line 441, in fit
    return super().fit(X, self._le.transform(y), sample_weight)
  File "/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/ensemble/_stacking.py", line 172, in fit
    self.stack_method_ = [
  File "/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/ensemble/_stacking.py", line 173, in <listcomp>
    self._method_name(name, est, meth)
  File "/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/ensemble/_stacking.py", line 108, in _method_name
    raise ValueError('Underlying estimator {} does not implement '
ValueError: Underlying estimator rf does not implement the method decision_function.

  warnings.warn("Estimator fit failed. The score on this train-test"
/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/model_selection/_validation.py", line 598, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/ensemble/_stacking.py", line 441, in fit
    return super().fit(X, self._le.transform(y), sample_weight)
  File "/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/ensemble/_stacking.py", line 172, in fit
    self.stack_method_ = [
  File "/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/ensemble/_stacking.py", line 173, in <listcomp>
    self._method_name(name, est, meth)
  File "/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/ensemble/_stacking.py", line 108, in _method_name
    raise ValueError('Underlying estimator {} does not implement '
ValueError: Underlying estimator rf does not implement the method decision_function.

  warnings.warn("Estimator fit failed. The score on this train-test"
/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/model_selection/_validation.py", line 598, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/ensemble/_stacking.py", line 441, in fit
    return super().fit(X, self._le.transform(y), sample_weight)
  File "/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/ensemble/_stacking.py", line 172, in fit
    self.stack_method_ = [
  File "/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/ensemble/_stacking.py", line 173, in <listcomp>
    self._method_name(name, est, meth)
  File "/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/ensemble/_stacking.py", line 108, in _method_name
    raise ValueError('Underlying estimator {} does not implement '
ValueError: Underlying estimator rf does not implement the method decision_function.

  warnings.warn("Estimator fit failed. The score on this train-test"
/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/model_selection/_search.py:922: UserWarning: One or more of the test scores are non-finite: [0.72058824        nan 0.75735294]
  warnings.warn(

Tuning the Logistic Regression Model with RandomizedSearchCV

/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/linear_model/_sag.py:328: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn("The max_iter was reached which means "

Tuning KNN model with RandomizedSearchCV

/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:696: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/model_selection/_validation.py", line 687, in _score
    scores = scorer(estimator, X_test, y_test)
  File "/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/metrics/_scorer.py", line 397, in _passthrough_scorer
    return estimator.score(*args, **kwargs)
  File "/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/base.py", line 500, in score
    return accuracy_score(y, self.predict(X), sample_weight=sample_weight)
  File "/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/neighbors/_classification.py", line 197, in predict
    neigh_dist, neigh_ind = self.kneighbors(X)
  File "/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/neighbors/_base.py", line 680, in kneighbors
    raise ValueError(
ValueError: Expected n_neighbors <= n_samples,  but n_samples = 66, n_neighbors = 73

  warnings.warn(
/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:696: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/model_selection/_validation.py", line 687, in _score
    scores = scorer(estimator, X_test, y_test)
  File "/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/metrics/_scorer.py", line 397, in _passthrough_scorer
    return estimator.score(*args, **kwargs)
  File "/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/base.py", line 500, in score
    return accuracy_score(y, self.predict(X), sample_weight=sample_weight)
  File "/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/neighbors/_classification.py", line 197, in predict
    neigh_dist, neigh_ind = self.kneighbors(X)
  File "/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/neighbors/_base.py", line 680, in kneighbors
    raise ValueError(
ValueError: Expected n_neighbors <= n_samples,  but n_samples = 66, n_neighbors = 73

  warnings.warn(
/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:696: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/model_selection/_validation.py", line 687, in _score
    scores = scorer(estimator, X_test, y_test)
  File "/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/metrics/_scorer.py", line 397, in _passthrough_scorer
    return estimator.score(*args, **kwargs)
  File "/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/base.py", line 500, in score
    return accuracy_score(y, self.predict(X), sample_weight=sample_weight)
  File "/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/neighbors/_classification.py", line 197, in predict
    neigh_dist, neigh_ind = self.kneighbors(X)
  File "/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/neighbors/_base.py", line 680, in kneighbors
    raise ValueError(
ValueError: Expected n_neighbors <= n_samples,  but n_samples = 65, n_neighbors = 73

  warnings.warn(
/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:696: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/model_selection/_validation.py", line 687, in _score
    scores = scorer(estimator, X_test, y_test)
  File "/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/metrics/_scorer.py", line 397, in _passthrough_scorer
    return estimator.score(*args, **kwargs)
  File "/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/base.py", line 500, in score
    return accuracy_score(y, self.predict(X), sample_weight=sample_weight)
  File "/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/neighbors/_classification.py", line 197, in predict
    neigh_dist, neigh_ind = self.kneighbors(X)
  File "/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/neighbors/_base.py", line 680, in kneighbors
    raise ValueError(
ValueError: Expected n_neighbors <= n_samples,  but n_samples = 65, n_neighbors = 73

  warnings.warn(
/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:696: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/model_selection/_validation.py", line 687, in _score
    scores = scorer(estimator, X_test, y_test)
  File "/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/metrics/_scorer.py", line 397, in _passthrough_scorer
    return estimator.score(*args, **kwargs)
  File "/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/base.py", line 500, in score
    return accuracy_score(y, self.predict(X), sample_weight=sample_weight)
  File "/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/neighbors/_classification.py", line 197, in predict
    neigh_dist, neigh_ind = self.kneighbors(X)
  File "/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/neighbors/_base.py", line 680, in kneighbors
    raise ValueError(
ValueError: Expected n_neighbors <= n_samples,  but n_samples = 66, n_neighbors = 73

  warnings.warn(
/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:696: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/model_selection/_validation.py", line 687, in _score
    scores = scorer(estimator, X_test, y_test)
  File "/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/metrics/_scorer.py", line 397, in _passthrough_scorer
    return estimator.score(*args, **kwargs)
  File "/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/base.py", line 500, in score
    return accuracy_score(y, self.predict(X), sample_weight=sample_weight)
  File "/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/neighbors/_classification.py", line 197, in predict
    neigh_dist, neigh_ind = self.kneighbors(X)
  File "/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/neighbors/_base.py", line 680, in kneighbors
    raise ValueError(
ValueError: Expected n_neighbors <= n_samples,  but n_samples = 66, n_neighbors = 97

  warnings.warn(
/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:696: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/model_selection/_validation.py", line 687, in _score
    scores = scorer(estimator, X_test, y_test)
  File "/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/metrics/_scorer.py", line 397, in _passthrough_scorer
    return estimator.score(*args, **kwargs)
  File "/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/base.py", line 500, in score
    return accuracy_score(y, self.predict(X), sample_weight=sample_weight)
  File "/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/neighbors/_classification.py", line 197, in predict
    neigh_dist, neigh_ind = self.kneighbors(X)
  File "/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/neighbors/_base.py", line 680, in kneighbors
    raise ValueError(
ValueError: Expected n_neighbors <= n_samples,  but n_samples = 66, n_neighbors = 97

  warnings.warn(
/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:696: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/model_selection/_validation.py", line 687, in _score
    scores = scorer(estimator, X_test, y_test)
  File "/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/metrics/_scorer.py", line 397, in _passthrough_scorer
    return estimator.score(*args, **kwargs)
  File "/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/base.py", line 500, in score
    return accuracy_score(y, self.predict(X), sample_weight=sample_weight)
  File "/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/neighbors/_classification.py", line 197, in predict
    neigh_dist, neigh_ind = self.kneighbors(X)
  File "/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/neighbors/_base.py", line 680, in kneighbors
    raise ValueError(
ValueError: Expected n_neighbors <= n_samples,  but n_samples = 66, n_neighbors = 97

  warnings.warn(
/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:696: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/model_selection/_validation.py", line 687, in _score
    scores = scorer(estimator, X_test, y_test)
  File "/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/metrics/_scorer.py", line 397, in _passthrough_scorer
    return estimator.score(*args, **kwargs)
  File "/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/base.py", line 500, in score
    return accuracy_score(y, self.predict(X), sample_weight=sample_weight)
  File "/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/neighbors/_classification.py", line 197, in predict
    neigh_dist, neigh_ind = self.kneighbors(X)
  File "/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/neighbors/_base.py", line 680, in kneighbors
    raise ValueError(
ValueError: Expected n_neighbors <= n_samples,  but n_samples = 65, n_neighbors = 97

  warnings.warn(
/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:696: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/model_selection/_validation.py", line 687, in _score
    scores = scorer(estimator, X_test, y_test)
  File "/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/metrics/_scorer.py", line 397, in _passthrough_scorer
    return estimator.score(*args, **kwargs)
  File "/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/base.py", line 500, in score
    return accuracy_score(y, self.predict(X), sample_weight=sample_weight)
  File "/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/neighbors/_classification.py", line 197, in predict
    neigh_dist, neigh_ind = self.kneighbors(X)
  File "/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/neighbors/_base.py", line 680, in kneighbors
    raise ValueError(
ValueError: Expected n_neighbors <= n_samples,  but n_samples = 65, n_neighbors = 79

  warnings.warn(
/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:696: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/model_selection/_validation.py", line 687, in _score
    scores = scorer(estimator, X_test, y_test)
  File "/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/metrics/_scorer.py", line 397, in _passthrough_scorer
    return estimator.score(*args, **kwargs)
  File "/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/base.py", line 500, in score
    return accuracy_score(y, self.predict(X), sample_weight=sample_weight)
  File "/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/neighbors/_classification.py", line 197, in predict
    neigh_dist, neigh_ind = self.kneighbors(X)
  File "/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/neighbors/_base.py", line 680, in kneighbors
    raise ValueError(
ValueError: Expected n_neighbors <= n_samples,  but n_samples = 65, n_neighbors = 97

  warnings.warn(
/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:696: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/model_selection/_validation.py", line 687, in _score
    scores = scorer(estimator, X_test, y_test)
  File "/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/metrics/_scorer.py", line 397, in _passthrough_scorer
    return estimator.score(*args, **kwargs)
  File "/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/base.py", line 500, in score
    return accuracy_score(y, self.predict(X), sample_weight=sample_weight)
  File "/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/neighbors/_classification.py", line 197, in predict
    neigh_dist, neigh_ind = self.kneighbors(X)
  File "/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/neighbors/_base.py", line 680, in kneighbors
    raise ValueError(
ValueError: Expected n_neighbors <= n_samples,  but n_samples = 66, n_neighbors = 79

  warnings.warn(
/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:696: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/model_selection/_validation.py", line 687, in _score
    scores = scorer(estimator, X_test, y_test)
  File "/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/metrics/_scorer.py", line 397, in _passthrough_scorer
    return estimator.score(*args, **kwargs)
  File "/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/base.py", line 500, in score
    return accuracy_score(y, self.predict(X), sample_weight=sample_weight)
  File "/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/neighbors/_classification.py", line 197, in predict
    neigh_dist, neigh_ind = self.kneighbors(X)
  File "/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/neighbors/_base.py", line 680, in kneighbors
    raise ValueError(
ValueError: Expected n_neighbors <= n_samples,  but n_samples = 66, n_neighbors = 79

  warnings.warn(
/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:696: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/model_selection/_validation.py", line 687, in _score
    scores = scorer(estimator, X_test, y_test)
  File "/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/metrics/_scorer.py", line 397, in _passthrough_scorer
    return estimator.score(*args, **kwargs)
  File "/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/base.py", line 500, in score
    return accuracy_score(y, self.predict(X), sample_weight=sample_weight)
  File "/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/neighbors/_classification.py", line 197, in predict
    neigh_dist, neigh_ind = self.kneighbors(X)
  File "/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/neighbors/_base.py", line 680, in kneighbors
    raise ValueError(
ValueError: Expected n_neighbors <= n_samples,  but n_samples = 66, n_neighbors = 79

  warnings.warn(
/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:696: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/model_selection/_validation.py", line 687, in _score
    scores = scorer(estimator, X_test, y_test)
  File "/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/metrics/_scorer.py", line 397, in _passthrough_scorer
    return estimator.score(*args, **kwargs)
  File "/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/base.py", line 500, in score
    return accuracy_score(y, self.predict(X), sample_weight=sample_weight)
  File "/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/neighbors/_classification.py", line 197, in predict
    neigh_dist, neigh_ind = self.kneighbors(X)
  File "/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/neighbors/_base.py", line 680, in kneighbors
    raise ValueError(
ValueError: Expected n_neighbors <= n_samples,  but n_samples = 65, n_neighbors = 79

  warnings.warn(
/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/model_selection/_search.py:922: UserWarning: One or more of the test scores are non-finite: [       nan 0.73235294 0.73235294 0.75808824 0.73235294 0.73235294
        nan 0.73235294 0.73235294        nan]
  warnings.warn(

Tuning Decision Tree model with RandomizedSearchCV


Tuning Random Forest model with RandomizedSearchCV


Tuning Boosting model with RandomizedSearchCV


Tuning Bagging model with RandomizedSearchCV


Tuning Stacking model with RandomizedSearchCV

/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/model_selection/_search.py:285: UserWarning: The total space of parameters 3 is smaller than n_iter=10. Running 3 iterations. For exhaustive searches, use GridSearchCV.
  warnings.warn(
/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/model_selection/_validation.py", line 598, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/ensemble/_stacking.py", line 441, in fit
    return super().fit(X, self._le.transform(y), sample_weight)
  File "/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/ensemble/_stacking.py", line 172, in fit
    self.stack_method_ = [
  File "/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/ensemble/_stacking.py", line 173, in <listcomp>
    self._method_name(name, est, meth)
  File "/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/ensemble/_stacking.py", line 108, in _method_name
    raise ValueError('Underlying estimator {} does not implement '
ValueError: Underlying estimator rf does not implement the method decision_function.

  warnings.warn("Estimator fit failed. The score on this train-test"
/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/model_selection/_validation.py", line 598, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/ensemble/_stacking.py", line 441, in fit
    return super().fit(X, self._le.transform(y), sample_weight)
  File "/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/ensemble/_stacking.py", line 172, in fit
    self.stack_method_ = [
  File "/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/ensemble/_stacking.py", line 173, in <listcomp>
    self._method_name(name, est, meth)
  File "/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/ensemble/_stacking.py", line 108, in _method_name
    raise ValueError('Underlying estimator {} does not implement '
ValueError: Underlying estimator rf does not implement the method decision_function.

  warnings.warn("Estimator fit failed. The score on this train-test"
/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/model_selection/_validation.py", line 598, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/ensemble/_stacking.py", line 441, in fit
    return super().fit(X, self._le.transform(y), sample_weight)
  File "/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/ensemble/_stacking.py", line 172, in fit
    self.stack_method_ = [
  File "/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/ensemble/_stacking.py", line 173, in <listcomp>
    self._method_name(name, est, meth)
  File "/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/ensemble/_stacking.py", line 108, in _method_name
    raise ValueError('Underlying estimator {} does not implement '
ValueError: Underlying estimator rf does not implement the method decision_function.

  warnings.warn("Estimator fit failed. The score on this train-test"
/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/model_selection/_validation.py", line 598, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/ensemble/_stacking.py", line 441, in fit
    return super().fit(X, self._le.transform(y), sample_weight)
  File "/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/ensemble/_stacking.py", line 172, in fit
    self.stack_method_ = [
  File "/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/ensemble/_stacking.py", line 173, in <listcomp>
    self._method_name(name, est, meth)
  File "/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/ensemble/_stacking.py", line 108, in _method_name
    raise ValueError('Underlying estimator {} does not implement '
ValueError: Underlying estimator rf does not implement the method decision_function.

  warnings.warn("Estimator fit failed. The score on this train-test"
/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/model_selection/_validation.py", line 598, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/ensemble/_stacking.py", line 441, in fit
    return super().fit(X, self._le.transform(y), sample_weight)
  File "/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/ensemble/_stacking.py", line 172, in fit
    self.stack_method_ = [
  File "/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/ensemble/_stacking.py", line 173, in <listcomp>
    self._method_name(name, est, meth)
  File "/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/ensemble/_stacking.py", line 108, in _method_name
    raise ValueError('Underlying estimator {} does not implement '
ValueError: Underlying estimator rf does not implement the method decision_function.

  warnings.warn("Estimator fit failed. The score on this train-test"
/home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/sklearn/model_selection/_search.py:922: UserWarning: One or more of the test scores are non-finite: [0.70808824        nan 0.70882353]
  warnings.warn(
2021-08-20 22:45:50.925643: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcuda.so.1
2021-08-20 22:45:54.041812: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:923] could not open file to read NUMA node: /sys/bus/pci/devices/0000:02:00.0/numa_node
Your kernel may have been built without NUMA support.
2021-08-20 22:45:54.050842: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1733] Found device 0 with properties:
pciBusID: 0000:02:00.0 name: NVIDIA GeForce MX130 computeCapability: 5.0
coreClock: 1.189GHz coreCount: 3 deviceMemorySize: 2.00GiB deviceMemoryBandwidth: 37.33GiB/s
2021-08-20 22:45:54.053073: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2021-08-20 22:45:54.056728: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcublas.so.11'; dlerror: libcublas.so.11: cannot open shared object file: No such file or directory
2021-08-20 22:45:54.057648: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcublasLt.so.11'; dlerror: libcublasLt.so.11: cannot open shared object file: No such file or directory
2021-08-20 22:45:54.111507: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcufft.so.10
2021-08-20 22:45:54.126846: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcurand.so.10
2021-08-20 22:45:54.127913: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcusolver.so.11'; dlerror: libcusolver.so.11: cannot open shared object file: No such file or directory
2021-08-20 22:45:54.128460: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcusparse.so.11'; dlerror: libcusparse.so.11: cannot open shared object file: No such file or directory
2021-08-20 22:45:54.129783: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudnn.so.8'; dlerror: libcudnn.so.8: cannot open shared object file: No such file or directory
2021-08-20 22:45:54.132682: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1766] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
2021-08-20 22:45:54.207056: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021-08-20 22:45:54.238826: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1258] Device interconnect StreamExecutor with strength 1 edge matrix:
2021-08-20 22:45:54.239017: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1264]

WARNING:tensorflow:Using temporary folder as model directory: /tmp/tmp5p7mqkzs
WARNING:tensorflow:From /home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/tensorflow/python/training/training_util.py:235: Variable.initialized_value (from tensorflow.python.ops.variables) is deprecated and will be removed in a future version.
Instructions for updating:
Use Variable.read_value. Variables in 2.X are initialized automatically both in eager and graph (inside tf.defun) contexts.
WARNING:tensorflow:From /home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/tensorflow/python/keras/layers/normalization.py:534: _colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
WARNING:tensorflow:From /home/jaineel/anaconda3/envs/SuicidePrediction/lib/python3.9/site-packages/tensorflow/python/keras/optimizer_v2/adagrad.py:87: calling Constant.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
2021-08-20 22:46:01.917015: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:923] could not open file to read NUMA node: /sys/bus/pci/devices/0000:02:00.0/numa_node
Your kernel may have been built without NUMA support.
2021-08-20 22:46:01.917897: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1733] Found device 0 with properties:
pciBusID: 0000:02:00.0 name: NVIDIA GeForce MX130 computeCapability: 5.0
coreClock: 1.189GHz coreCount: 3 deviceMemorySize: 2.00GiB deviceMemoryBandwidth: 37.33GiB/s
2021-08-20 22:46:01.918183: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1766] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
2021-08-20 22:46:02.614104: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1258] Device interconnect StreamExecutor with strength 1 edge matrix:
2021-08-20 22:46:02.614209: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1264]      0
2021-08-20 22:46:02.614503: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1277] 0:   N
2021-08-20 22:46:02.768077: I tensorflow/core/platform/profile_utils/cpu_utils.cc:114] CPU Frequency: 1800005000 Hz
2021-08-20 22:46:17.916395: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:923] could not open file to read NUMA node: /sys/bus/pci/devices/0000:02:00.0/numa_node
Your kernel may have been built without NUMA support.
2021-08-20 22:46:17.917632: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1733] Found device 0 with properties:
pciBusID: 0000:02:00.0 name: NVIDIA GeForce MX130 computeCapability: 5.0
coreClock: 1.189GHz coreCount: 3 deviceMemorySize: 2.00GiB deviceMemoryBandwidth: 37.33GiB/s
2021-08-20 22:46:17.917807: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1766] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
2021-08-20 22:46:17.917850: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1258] Device interconnect StreamExecutor with strength 1 edge matrix:
2021-08-20 22:46:17.917923: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1264]      0
2021-08-20 22:46:17.918023: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1277] 0:   N
2021-08-20 22:46:20.115957: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:923] could not open file to read NUMA node: /sys/bus/pci/devices/0000:02:00.0/numa_node
Your kernel may have been built without NUMA support.
2021-08-20 22:46:20.117191: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1733] Found device 0 with properties:
pciBusID: 0000:02:00.0 name: NVIDIA GeForce MX130 computeCapability: 5.0
coreClock: 1.189GHz coreCount: 3 deviceMemorySize: 2.00GiB deviceMemoryBandwidth: 37.33GiB/s
2021-08-20 22:46:20.117318: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1766] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
2021-08-20 22:46:20.117434: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1258] Device interconnect StreamExecutor with strength 1 edge matrix:
2021-08-20 22:46:20.117519: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1264]      0
2021-08-20 22:46:20.117609: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1277] 0:   N
accuracyDict:

{
 "Log_Reg_mod_GSCV": 85.71428571428571,
 "KNN_GSCV": 90.47619047619048,
 "DecisionTree_GSCV": 80.95238095238095,
 "RandomForest_GSCV": 85.71428571428571,
 "AdaBoost_GSCV": 80.95238095238095,
 "Bagging_GSCV": 90.47619047619048,
 "Stacking_GSCV": 90.47619047619048,
 "Log_Reg_mod_RSCV": 85.71428571428571,
 "KNN_RSCV": 80.95238095238095,
 "DecisionTree_RSCV": 80.95238095238095,
 "RandomForest_RSCV": 80.95238095238095,
 "AdaBoost_RSCV": 80.95238095238095,
 "Bagging_RSCV": 80.95238095238095,
 "Stacking_RSCV": 80.95238095238095,
 "DNN Classifier": 47.61904776096344
}
/mnt/c/Users/JP/Documents/Mental-Geek_Leap/Suicide-Prediction/src/AccuracyBarGraph.py:9: UserWarning: Starting a Matplotlib GUI outside of the main thread will likely fail.
  plt.figure(figsize=(12,8))
Time Taken by Grid Search:  886.9652733802795 Seconds
Time Taken by Random Search:  41.577512979507446 Seconds
Time Taken by DNN Classifier:  30.005882263183594 Seconds
127.0.0.1 - - [20/Aug/2021 22:46:21] "GET /download HTTP/1.1" 200 -
127.0.0.1 - - [20/Aug/2021 22:46:21] "GET /static/css/download.css HTTP/1.1" 304 -
127.0.0.1 - - [20/Aug/2021 22:46:22] "GET /static/css/background.jpg HTTP/1.1" 304 -
127.0.0.1 - - [20/Aug/2021 22:48:49] "POST /download_result HTTP/1.1" 200 -
127.0.0.1 - - [20/Aug/2021 22:48:55] "POST /download_graph HTTP/1.1" 200 -
^Z
[1]+  Stopped                 python3 app.py